###########################################################
#   Description: Compile OpenWrt by GitHub Actions        #
#   Based on: https://github.com/P3TERX/Actions-OpenWrt   #
#   Author: muink                                         #
###########################################################

name: 21_02-x86_64

### 以下内容请保持不变 ( 请修改下方的 [环境变量设置] )
on:
  repository_dispatch:
  workflow_dispatch:
### 控制部分结束 ( 以上内容请保持不变 )

  push:
    branches: [ master ]
    paths:
    - 'Makefile'

  #schedule:
  #  - cron: 0 8 * * 5

  watch:
    types: [started]

### 环境变量设置
env:
# 编译版本信息参数
  VERSIONS: '21.02.5'
  TARGET: 'x86/64'
  ARCH: 'x86_64'
# 使用 GPG 签名 Packages (非必要)
  GPG_SIGN: true
# Pre-download Libraries
  PRE_DOWNLOAD: false
# 删除无用文件以增加编译空间
  DELETE_USELESS_FILES: true
# 删除早期的 workflow 任务
  DELETE_OLD_WORKFLOW: true
### 结束

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: false

jobs:
  compile:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To push a branch
      # pull-requests: write  # To create a PR from that branch
      actions: write

    steps:
    - name: Maximize Build Space
      if: env.DELETE_USELESS_FILES == 'true' && !cancelled()
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 5120
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'

    - name: Initialize Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get update
        sudo -E apt-get -y install curl tar gzip bash gpg build-essential clang flex bison g++ gawk gcc-multilib gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget
        sudo timedatectl set-timezone "Asia/Shanghai"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        if [ "${{ env.DELETE_USELESS_FILES }}" == true ]
        then
            docker rmi $(docker images -q)
            sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php
            sudo -E apt-get -y autoremove --purge
            sudo -E apt-get clean
        fi

    - name: Checkout
      uses: actions/checkout@v3
      with:
        lfs: true
        submodules: true

    - name: Initialize OpenWRT SDK
      shell: bash
      run: |
        mkdir -p "/workdir/DL"
        sdk=$(curl --connect-timeout 10 --retry 3 -sSL https://downloads.openwrt.org/releases/$VERSIONS/targets/$TARGET | grep 'openwrt-sdk' | sed -En 's|.+\bhref="([^"]+)".+|\1|p')
        curl --connect-timeout 10 --retry 3 -sSL -o "/workdir/$sdk" https://downloads.openwrt.org/releases/$VERSIONS/targets/$TARGET/$sdk
        [ "$?" == 0 ] && {
          tar -C "/workdir" -xf "/workdir/$sdk"
          rm -f "/workdir/$sdk"
          mv "/workdir/${sdk%.tar.*}" "/workdir/$VERSIONS"
          pushd "/workdir/$VERSIONS" && umask 022
          pushd "/workdir/$VERSIONS/package" && umask 022
          ln -s "$GITHUB_WORKSPACE" "fantastic-packages"
          popd
          rm -rf dl 2>/dev/null
          ln -s "/workdir/DL" dl
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig
          popd
        }

    - name: Pre-download Libraries
      shell: bash
      if: env.PRE_DOWNLOAD == 'true' && !cancelled()
      run: |
        [ -d "/workdir/$VERSIONS" ] && {
          pushd "/workdir/$VERSIONS"
          make download -j$(($(nproc)+1))
          popd
        }

    - name: Build Packages
      shell: bash
      run: |
        [ -d "/workdir/$VERSIONS" ] && {
          pushd "/workdir/$VERSIONS"
          make package/fantastic-packages/compile V=99
          popd
        }

    - name: Checkout Packages
      shell: bash
      env:
        USIGN_ID: '53FF2B6672243D28'
        USIGN_KEY: ${{secrets.USIGN_53FF2B6672243D28}}
        GPG_ID: 'A5F2461EC8F6DCAA'
        GPG_PW: ${{secrets.GPG_PW_A5F2461EC8F6DCAA}}
        GPG_KEY: ${{secrets.GPG_A5F2461EC8F6DCAA}}
      run: |
        export PATH="$PATH:/workdir/$VERSIONS/staging_dir/host/bin"
        sudo chmod -R +x "/workdir/$VERSIONS/staging_dir/host/bin/"
        export MKHASH="/workdir/$VERSIONS/staging_dir/host/bin/mkhash"
        sudo chmod +x "/workdir/$VERSIONS/scripts/ipkg-make-index.sh"
        #
        eval $(cat $GITHUB_WORKSPACE/Makefile|sed -En '/^\s*DEPENDS/,/^endef/{/^\s*(DEPENDS:=|\+)/p}'|tr '\n' ' '|sed -E "s|[:+\\]||g;s|\bluci-app-|luci-*-|g;s|\s+| |g;s|=|='|;s|\s*$|'|")
        REGEXP=$(echo $DEPENDS|sed 's| |*.ipk -or -name |g;s|^|-name |;s|$|*.ipk|')
        mkdir -p "$GITHUB_WORKSPACE/releases" 2>/dev/null
        if [ -d "/workdir/$VERSIONS" ]; then
          mkdir -p "$GITHUB_WORKSPACE/releases/$ARCH/#$VERSIONS/packages" 2>/dev/null
          eval $(find "/workdir/$VERSIONS/bin/packages/$ARCH/" -type f $REGEXP | sed -E 's|^(.+)$|mv -f "\1" "$GITHUB_WORKSPACE/releases/$ARCH/#$VERSIONS/packages/"; |g;s|\$|\$|g')
          pushd "$GITHUB_WORKSPACE/releases/$ARCH/#$VERSIONS/packages"
          # ref: SDK/package/Makefile:index:
          "/workdir/$VERSIONS/scripts/ipkg-make-index.sh" . 2>&1 > Packages.manifest
          grep -vE '^(Maintainer|LicenseFiles|Source|SourceName|Require|SourceDateEpoch)' Packages.manifest > Packages
          case "$(((64 + $(stat -L -c%s Packages)) % 128))" in 110|111)
            # WARNING: Applying padding in $$d/Packages to workaround usign SHA-512 bug!
            { echo ""; echo ""; } >> Packages;;
          esac
          gzip -9nc Packages > Packages.gz
          # ref: SDK/package/Makefile:CONFIG_SIGNED_PACKAGES
          usign -S -m Packages -s <(echo "${USIGN_KEY}")
          cp -f "$GITHUB_WORKSPACE/keys/usign/${USIGN_ID}.pub" ../${USIGN_ID}.pub
        USIGN_PUBKEY="$(cat ../${USIGN_ID}.pub)"
        cat <<- EOF > ../${USIGN_ID}.sh
        #!/bin/sh
        KEYID=${USIGN_ID}
        mkdir -p /etc/opkg/keys 2>/dev/null
        cat <<- PUBKEY > /etc/opkg/keys/\${KEYID,,}
        ${USIGN_PUBKEY}
        PUBKEY
        EOF
          if [ "${{env.GPG_SIGN}}" == true ]; then
            gpg --batch --pinentry-mode=loopback --yes --passphrase "$(echo -n "${GPG_PW}")" --import <(echo "${GPG_KEY}")
            echo "$(sed 's|\s||g' "$GITHUB_WORKSPACE/keys/gpg/${GPG_ID}.finger"):6:" | gpg --import-ownertrust
            gpg -u ${GPG_ID} --batch --pinentry-mode=loopback --yes --passphrase "$(echo -n "${GPG_PW}")" -a -o Packages.asc --detach-sign Packages
            cp -f "$GITHUB_WORKSPACE/keys/gpg/${GPG_ID}.finger" ../${GPG_ID}.gpg.finger
            cp -f "$GITHUB_WORKSPACE/keys/gpg/${GPG_ID}.pub" ../${GPG_ID}.gpg.pub
            cp -f "$GITHUB_WORKSPACE/keys/gpg/${GPG_ID}.rev" ../${GPG_ID}.gpg.rev
          fi
          popd
        fi

    - name: Commit and push Packages
      env:
        Branch: gh-pages
      run: |
        git config --local user.name "GitHub Action"
        git config --local user.email "actions-user@users.noreply.github.com"
        git remote update
        git fetch --no-tags --prune --no-recurse-submodules --depth=1 origin $Branch
        git checkout -B $Branch refs/remotes/origin/$Branch
        rm -rf "$GITHUB_WORKSPACE/releases/$ARCH/${VERSIONS%.*}" 2>/dev/null
        mv "$GITHUB_WORKSPACE/releases/$ARCH/#$VERSIONS" "$GITHUB_WORKSPACE/releases/$ARCH/${VERSIONS%.*}"
        ./prenodes.sh
        git add releases/$ARCH
        git diff-index --cached --quiet HEAD -- || (git commit -m "Update $ARCH" && git push)

    - name: Delete old Workflow Runs
      uses: GitRML/delete-workflow-runs@main
      if: env.DELETE_OLD_WORKFLOW == 'true' && !cancelled()
      with:
        retain_days: 1
        keep_minimum_runs: 3
